script: Use a _working_ 5.1 schema location
When using a literal file system reference rather than a catalog
reference, you need to use file:// in front of the path or DAPS will
give you this:
> ERROR: Could not determine the DocBook 5 schema location by resolving
> "/usr/share/xml/docbook/schema/rng/5.1/docbookxi.rng" via xmlcatalog

Let's just use the catalog though, that's more portable anyway (as if
that were necessary).